apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore-from-s3
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: restore-runner
          image: alpine:3.20
          command:
            - /bin/sh
            - -c
            - |
              set -e
              apk add --no-cache mysql-client aws-cli gzip

              aws s3 cp s3://dr-mysql-backups-905418200087/mysql-backups/backup_2026-08-09_20-37-47.sql.gz /tmp/backup.sql.gz
              gunzip /tmp/backup.sql.gz

              mysql -h $MYSQL_DATABASE_HOST \
                    -u $MYSQL_DATABASE_USER \
                    -p"$DB_PASS" \
                    $MYSQL_DATABASE_DB < /tmp/backup.sql

              echo "Restore complete."
          envFrom:
            - configMapRef:
                name: flask-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE_PASSWORD