apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-password-spc
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: mysql-secret
      type: Opaque
      data:
        - objectName: mysql-admin-password
          key: MYSQL_DATABASE_PASSWORD # Aligned to match the deployment
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<value from Azure CLI>"
    keyvaultName: "<value from terraform output>"
    tenantId: "<value from Azure CLI>"
    objects: |
      array:
        - |
          objectName: mysql-admin-password
          objectType: secret