apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: flask-app
  newName: flaskappacrdev.azurecr.io/flask-app
  newTag: 2026-08-09-31318591519
patches:
- patch: |-
    - op: replace
      path: /data/MYSQL_DATABASE_HOST
      value: mysql-flaskapp-dev.mysql.database.azure.com
  target:
    kind: ConfigMap
    name: flask-config
