apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- flask-config.yml
- ingress.yml
- db-schema-configmap.yml
- db-schema-job.yml
images:
- name: flask-app
  newName: flaskappacrdev.azurecr.io/flask-app
  newTag: 2026-08-06-31092864926
