apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- flask-configMap.yml
- ingress.yml
- db-schema-configmap.yml
- db-schema-job.yml
images:
- name: flask-app
  newName: flaskappacrdev.azurecr.io/flask-app
  newTag: 2026-08-06-31092864926
patches:
  - target:
      kind: ConfigMap
      name: flask-config
    patch: |-
      - op: replace
        path: /data/MYSQL_DATABASE_HOST
        value: <rds-endpoint-from-terraform-output>