apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
data:
  MYSQL_DATABASE_DB: BucketList        # matches mysql_database_name from terraform
  MYSQL_DATABASE_HOST: placeholder-host  
  MYSQL_DATABASE_USER: mysqladmin    # matches var.mysql_admin_username